### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#16] opened 2019-08-06 19:30 UTC
Different version should be under same object ID, just 

`https://data.glygen.org/DSBCO_000001/v-1.0.12`

vs 

`https://data.glygen.org/DSBCO_000001/v-1.0.13`

That way you can access. As we have now, we update a step in the pipeline step, you would be changing the version of the BCO. AS it is now, the only way to do this would be to create an additional BCO.

**Comment by jpat1546** [comment] 2019-08-29 21:14
To streamline the versioning process for authors : “Create Another Version” option adjacent to "Edit Object"

**Comment by openbox-bio** [comment] 2019-08-31 10:44
Need to discuss this requirement and its priority.

**Comment by jpat1546** [comment] 2019-09-03 20:52
@openbox-bio let's discuss tomorrow if you have time?

**Comment by openbox-bio** [comment] 2019-09-20 10:42
Can we discuss on call today if possible?

**Comment by jpat1546** [comment] 2019-09-20 19:39
this is a near duplicate of #34. low priority for this next iteration.

**Comment by carmstrong1gw** [comment] 2020-08-25 18:17
Moved to API security doc.

**Closed by carmstrong1gw** 2020-08-25 18:17 UTC
Labels: Discussion
